### ISSUE TITLE
Single digit hour syntax and 24

### ISSUE THREAD

**Issue by dricholm** [meyfa/line-chat-parser#3]
I found two problems with parsing messages hour:

1. Currently it uses this regexp for messages: `/^(\d{2}):(\d{2})(?: |\t)(\S.+)/`, this will only match lines where the hour has two digits. In case of a mobile phone exported log hours can be from 1-24. (In this case it was Japanese locale, I haven't tested others yet) That means single digit hour messages will probably be added to the message before.
2. Another difference because of app export or locale is that 24 is a valid hour, for example: "24:00", which means the start of a day. Because JavaScripts hours are from 0-23, 24 would mean the message appears a day after the date in the log.

Here are two tests which will fail now:
 ```js
it("should process hours with one digit", function () {
    var obj = new LineChatParser(["foo"]);
    obj.currentDate = new Date(2018, 3, 19);
    obj.process("5:06\tfoo\thello world");
    expect(obj.currentMessage.date).to.deep.equal(new Date(2018, 3, 19, 5, 6));
});

it("should process hour in case of 24", function () {
    var obj = new LineChatParser(["foo"]);
    obj.currentDate = new Date(2018, 3, 19);
    obj.process("24:53\tfoo\thello world");
    expect(obj.currentMessage.date).to.deep.equal(new Date(2018, 3, 19, 0, 53));
});
```

The solutions I thought of:
1. Allow at least 1 and at most 2 digits, so: `^(\d{1,2}):(\d{2})(?: |\t)(\S.+)`
2. Mod the hours with 24 and it should be correct: `var hours = parseInt(match[1], 10) % 24`

If you agree with these, I can submit a PR too.

Thank you!

**Comment by meyfa** [comment]
Very good report! Yes, your proposed solutions seem like good steps to take. Thanks for bringing this up. I'd be happy to receive your PR :-)
