### ISSUE TITLE
Unnecessary users argument in case of tab separators

### ISSUE THREAD

**Issue by dricholm** [meyfa/line-chat-parser#5]
As we talked about it in a previous issue, users argument is unnecessary in case of tab separators as user names cannot contain tabs. I tried placing a tab in my name and it was removed from the name. But messages can contain tabs.

I have made a change, which works with the same function. The users argument will be made optional. I can submit a PR if that way is okay and we could further discuss the modification there.

**Comment by meyfa** [comment]
Thanks for testing this thoroughly, that way we can be sure it works. I think just making the argument optional is indeed least intrusive, it feels like the way to go. Feel free to submit the PR.
