### ISSUE TITLE
Parsing message with first empty line and without users argument

### ISSUE THREAD

**Issue by dricholm** [meyfa/line-chat-parser#8]
I found an error, which is the result of my previous pull request:
```
TypeError: Cannot read property 'reduce' of undefined
 at LineChatParser.process (index.js:55:55)
```

I looked into it and it happens when:
* no users argument is given
* first line of the message is empty: just a line break

Because no users argument is given, the regex with 4 groups will be used but the last group which should be the message is undefined because the message only contains a line break.

Currently setting the author is done with this line:
```js
var author = match[4] ? match[3] : this.users.reduce(function (previousValue, user) {
            if (user.length > previousValue.length && match[3].indexOf(user) === 0) {
                return user;
            }
            return previousValue;
        }, "");
```

So the solution I thought of could be this: (replacing the condition to check if users are given)
```js
var author = typeof this.users === "undefined" ? match[3] : this.users.reduce(function (previousValue, user) {
            if (user.length > previousValue.length && match[3].indexOf(user) === 0) {
                return user;
            }
            return previousValue;
        }, "");
```

Making the conditions different outside and inside was my mistake, sorry.

If this seems okay, I could submit a PR. But I would gladly hear your opinion about this. Could the part inside `if (match)` be somehow refactored to be more easily readable maybe.

**Comment by meyfa** [comment]
I pushed a failing test case for this issue and will look into the best way of approaching it.

**Comment by meyfa** [comment]
I tried different ways and they all result in more or less the same logic that you proposed. The commit I just made fixes the issue, but I will keep it open so you can decide for yourself whether it should be marked as fixed just yet.

I could not simplify the if/else statement much, but was able to shorten the RegExes slightly by using character groups.

**Comment by dricholm** [comment]
I think your fix is okay. Also you are right about the RegEx shortenings.

Thank you for the quick response and fix!
